services:
    my-rabbitmq-service: # your service name - RabbitMQ service (can customize name as needed)
        image: rabbitmq:3-management # Using RabbitMQ image with management plugin in docker hub
        container_name: my-rabbitmq # your container name (can customize name as needed)
        ports:
            - "5672:5672"   # RabbitMQ default port
            - "15672:15672" # RabbitMQ management UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
    my-jenkins:
        image: jenkins/jenkins:lts
        container_name: my-jenkins
        restart: unless-stopped
        ports:
            - "8080:8080" # UI jenkins
            - "50000:50000" # Agent port
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/rin/docker.sock/var/run/docker.sock # allow jenkins to use docker host
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false #disable first setup, if wanting to use jenkins without setup wizard
    spring-boot-demo:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./spring-artifacts:/ap/jar
        ports:
            - "8081:8080" # Spring Boot application port
volumes:
    jenkins_home: # create named volume