spring:
    application:
                name:distant-class
    datasource:
            url: jdbc:mysql://localhost:3306/database_name?useSSL=false&serverTimezone=UTC
            username: your_username
            password: your_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
