spring:
    profiles:
        active: local  # Mặc định chạy local
    datasource:
        url: jdbc:mysql://localhost:3306/distant_class?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: dev
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
api:
    base:
        path: /api/v1
server:
    port: 8080
        bc.Driver
